### ISSUE TITLE
Maximum Binary Tree

### ISSUE THREAD

**Issue by Chaitralikore** [Mozilla-Campus-Club-Cummins/HacktoberFest23_MozillaCCEW#103]
You are given an integer array nums with no duplicates. A maximum binary tree can be built recursively from nums using the following algorithm:

Create a root node whose value is the maximum value in nums.
- Recursively build the left subtree on the subarray prefix to 
  the left of the maximum value.
- Recursively build the right subtree on the subarray suffix 
  to the right of the maximum value.
- Return the maximum binary tree built from nums

**Comment by akanksha1131** [comment]
Can you please assign this to me?
Akanksha Kale
Cummins
TY IT UEC2021139

**Comment by sejalphatangare** [comment]
Hi! pls assign this issue to me
Sejal Phatangare
UCE2021457
Cummins 
TY

**Comment by Chaitralikore** [comment]
Hi! @sejalphatangare  you can work on only one issue at a time.

**Comment by Chaitralikore** [comment]
@sejalphatangare you can work on this issue
The deadline is 21st oct'23, 11:59pm 
Happy contributing!!
