### ISSUE TITLE
Airplane Seat Assignment Probability 

### ISSUE THREAD

**Issue by Chaitralikore** [Mozilla-Campus-Club-Cummins/HacktoberFest23_MozillaCCEW#105]
n passengers board an airplane with exactly n seats. The first passenger has lost the ticket and picks a seat randomly. But after that, the rest of the passengers will:

• Take their own seat if it is still available, and
• Pick other seats randomly when they find their seat 
  occupied

Return the probability that the nth person gets his own seat.

**Comment by bargeshreeya** [comment]
I would like to work on this issue .
Name- Shreeya Barge 
TY IT - 810

**Comment by Chaitralikore** [comment]
@bargeshreeya you can work on this issue. 
The deadline is 17th Oct'23, 11:59pm

**Comment by bhairavibhuyar** [comment]
Hello, I would like to work on this issue. Can you please assign it to me?
Bhairavi Bhuyar
UCE2021404
Third Year
