### ISSUE TITLE
Anagram Checker

### ISSUE THREAD

**Issue by harshadagd** [Mozilla-Campus-Club-Cummins/HacktoberFest23_MozillaCCEW#111]
Create a function that checks if two given strings are anagrams of each other. Anagrams are words or phrases formed by rearranging the letters of another.

**Comment by Subhashini014** [comment]
Could you please assign me this issue.

**Comment by Dineshraju3435** [comment]
@harshadagd  can you assign this to me

**Comment by srushtikage** [comment]
Hello i want to work on this issue can u please assign it to me.
Srushti Kage 
UCE2022531
Second year

**Comment by harshadagd** [comment]
> Hello i want to work on this issue can u please assign it to me. Srushti Kage UCE2022531 Second year

Yay

**Comment by harshadagd** [comment]
> Hello i want to work on this issue can u please assign it to me. Srushti Kage UCE2022531 Second year

heyy @srushtikage I have asssigned you the issue, create a PR by tagging this issue. Happy contribution.
