### ISSUE TITLE
Find the Intersection of Two Arrays

### ISSUE THREAD

**Issue by harshadagd** [Mozilla-Campus-Club-Cummins/HacktoberFest23_MozillaCCEW#113]
Implement a function that finds the common elements between two arrays and returns them in a new array.

**Comment by RutvikaWagh** [comment]
I would like to work on this issue. Here are my details:
Name : Rutvika Wagh
CNO: UCE2022669
Year : Second Year

**Comment by Dineshraju3435** [comment]
can you assign this to me plss @harshadagd

**Comment by srushtikage** [comment]
Hello i want to work on this issue can u please assign it to me.
Srushti Kage
UCE2022531
Second year

**Comment by schauna7** [comment]
I would like to work on this issue. Here are my details:
Name : Schauna singh
CNO: UIT2022860
Year : Second Year

**Comment by harshadagd** [comment]
> I would like to work on this issue. Here are my details: Name : Rutvika Wagh CNO: UCE2022669 Year : Second Year

sure

**Comment by harshadagd** [comment]
> I would like to work on this issue. Here are my details: Name : Rutvika Wagh CNO: UCE2022669 Year : Second Year

hey @RutvikaWagh I have assigned you the issue. Create a PR by tagging this issue.
