### ISSUE TITLE
Longest Substring Without Repeating Characters

### ISSUE THREAD

**Issue by harshadagd** [Mozilla-Campus-Club-Cummins/HacktoberFest23_MozillaCCEW#17]
Given a string, find the length of the longest substring without repeating characters.

**Comment by Vybhavigithub** [comment]
@harshadagd could you please assign this issue to me

**Comment by bhairavibhuyar** [comment]
Hello, I would like to work on this issue. Can you please assign it to me?
Bhairavi Bhuyar
UCE2021404
Third Year

**Comment by harshadagd** [comment]
> @harshadagd could you please assign this issue to me

**Comment by harshadagd** [comment]
> Hello, I would like to work on this issue. Can you please assign it to me? Bhairavi Bhuyar UCE2021404 Third Year

hey @bhairavibhuyar I have assigned you this issue, Create a PR by tagging this issue. Happy contribution
