### ISSUE TITLE
write a program to print addition, subtraction, multiplication of 3 by 3 matrix.

### ISSUE THREAD

**Issue by 51tejalhajari** [Mozilla-Campus-Club-Cummins/HacktoberFest23_MozillaCCEW#27]

**Comment by sharwaritijare** [comment]
Hey could you please assign me this issue.
UEC2023260 FY
Sharwari

**Comment by sharwaritijare** [comment]
@51tejalhajari I have completed the task, can you please review it?

**Comment by RiRa25** [comment]
Hello i want to work on this issue can u please assign it to me.
Richa Rathi
UEC2022324
Second year

**Comment by RiddhiPardeshi** [comment]
Can you assign me this issue
UEC2023337
Riddhi Pardeshi

**Comment by Siddhipardeshii** [comment]
Can you, please assign me this issue? 
UIT2023849
Siddhi Pardeshi
FY IT
