### ISSUE TITLE
write a code to find the middle element in a singly linked list.

### ISSUE THREAD

**Issue by 51tejalhajari** [Mozilla-Campus-Club-Cummins/HacktoberFest23_MozillaCCEW#29]

**Comment by schauna7** [comment]
Can you assign me this issue?
Name : Schauna singh
UNO.: UIT2022860
SY IT

**Comment by 51tejalhajari** [comment]
Yes you can work on this issue

**Comment by schauna7** [comment]
> Yes you can work on this issue
i am done with the code but am not aware what processto follow  to make changes in the file(issue) can you please guide me

**Comment by 51tejalhajari** [comment]
You can refer to the document or video  provided in mail for
convenience.check in Mozilla club mail.

**Comment by schauna7** [comment]
Yes i did refer, i have worked on this issue and pulled request please check
