### ISSUE TITLE
All about Op-Amp.

### ISSUE THREAD

**Issue by Vaishnavi-gaikawad** [Mozilla-Campus-Club-Cummins/HacktoberFest23_MozillaCCEW#40]
Make a Word doc. of 2-3 pages which has all the information about Op-Amp to understand the topic.

**Comment by saakshii12** [comment]
Hello, 
Can you assign this issue to me?
Sakshi Umredkar
SY Instru - UIN2022764

**Comment by Vaishnavi-gaikawad** [comment]
@saakshii12 you can work on this issue.

**Comment by Arpitalite** [comment]
hii 
can you plzz assign this issue to me ??
Arpita  Kumbhar 
SY entc UEC2022236

**Comment by saakshii12** [comment]
Hey I have created a PR please check #141
