### ISSUE TITLE
Cycle in Linked list

### ISSUE THREAD

**Issue by Lavanyawaghulde** [Mozilla-Campus-Club-Cummins/HacktoberFest23_MozillaCCEW#49]
Write a program in java to detect if linked list has a cycle or not

**Comment by bhairavibhuyar** [comment]
Hello, I would like to work on this issue. Can you please assign it to me?
Bhairavi Bhuyar
UCE2021404
Third Year

**Comment by Lavanyawaghulde** [comment]
@bhairavibhuyar You have already been assigned an issue. You can work on only one issue at a time. You can comment later if you still wish to contribute in this issue.

**Comment by bhairavibhuyar** [comment]
@Lavanyawaghulde Hey, my pull request for the previous issue has been merged, can you please assign me this one now?

**Comment by Lavanyawaghulde** [comment]
@bhairavibhuyar Sure. You have been assigned this issue. You are requested to submit a solution within span of two days.
