### ISSUE TITLE
Fibonacci series

### ISSUE THREAD

**Issue by Lavanyawaghulde** [Mozilla-Campus-Club-Cummins/HacktoberFest23_MozillaCCEW#51]
Write a java program to generate Fibonacci series till a number of your choice using recursion

**Comment by preeti-hatapaki** [comment]
Can you assign me this issue?
Name -> Preeti Hatapaki
UNo -> UIT2022855
SY IT

**Comment by Lavanyawaghulde** [comment]
@preeti-hatapaki This issue has been assigned to you. Make sure to submit solution within span of 2 days.

**Comment by preeti-hatapaki** [comment]
@Lavanyawaghulde I have completed the task ,Please review it .

**Comment by Lavanyawaghulde** [comment]
@preeti-hatapaki Great job! You have successfully completed your first issue. You can proceed with the second.
