### ISSUE TITLE
Spiral Matrix

### ISSUE THREAD

**Issue by saeegade12** [Mozilla-Campus-Club-Cummins/HacktoberFest23_MozillaCCEW#55]
Given an m x n matrix, return all elements of the matrix in spiral order.
Input: matrix = [[1,2,3],[4,5,6],[7,8,9]]
Output: [1,2,3,6,9,8,7,4,5]

**Comment by sharwaritijare** [comment]
Hey could you please assign me this issue.
UEC2023260 FY 
Sharwari Tijare

**Comment by saeegade12** [comment]
Yes, I have assigned it to you.
