### ISSUE TITLE
Trapping Rain Water

### ISSUE THREAD

**Issue by anu-shka-k** [Mozilla-Campus-Club-Cummins/HacktoberFest23_MozillaCCEW#66]
Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.

![rainwatertrap](https://github.com/Mozilla-Campus-Club-Cummins/HacktoberFest23_MozillaCCEW/assets/85599195/4baf676b-f404-41d6-b527-bda50a000d69)

Testcases:
Input: height = [0,1,0,2,1,0,1,3,2,1,2,1]
Output: 6
Explanation: The above elevation map (black section) is represented by array [0,1,0,2,1,0,1,3,2,1,2,1]. In this case, 6 units of rain water (blue section) are being trapped.

Input: height = [4,2,0,3,2,5]
Output: 9

**Comment by Subhashini014** [comment]
Could you please assign me this issue.

**Comment by anu-shka-k** [comment]
I'm sorry this repository is open only for students of Cummins college of engineering for women.

**Comment by srushtikage** [comment]
Hello can u please assign me this issue i want to work on it.
Srushti Kage
UCE2022531
Second year

**Comment by anu-shka-k** [comment]
Hi @srushtikage  , I have assigned this issue to you. Please submit a PR in the next 2 days.
