### ISSUE TITLE
Symmetric Tree

### ISSUE THREAD

**Issue by anu-shka-k** [Mozilla-Campus-Club-Cummins/HacktoberFest23_MozillaCCEW#67]
Given the root of a binary tree, check whether it is a mirror of itself (i.e., symmetric around its center).

Testcases:
![image](https://github.com/Mozilla-Campus-Club-Cummins/HacktoberFest23_MozillaCCEW/assets/85599195/e88ef912-9fd0-4cc5-8195-c97a675c23c2)
Input: root = [1,2,2,3,4,4,3]
Output: true

![image](https://github.com/Mozilla-Campus-Club-Cummins/HacktoberFest23_MozillaCCEW/assets/85599195/fc27ef7d-01b0-4036-8208-559d3ee7f62b)
Input: root = [1,2,2,null,3,null,3]
Output: false

**Comment by akanksha1131** [comment]
Can you please assign this to me?
Akanksha Kale TY IT Cummins

**Comment by anu-shka-k** [comment]
Hi @akanksha1131 , I have assigned this issue to you. Please submit a PR in the next 2 days.
