### ISSUE TITLE
write an algorithm for infix to postfix conversion using stack.

### ISSUE THREAD

**Issue by 51tejalhajari** [Mozilla-Campus-Club-Cummins/HacktoberFest23_MozillaCCEW#85]

**Comment by isha0904** [comment]
Can you assign me this issue?
Name -> Isha Baviskar
Cno. -> UCE2022427
SY Comp

**Comment by schauna7** [comment]
Can you assign me this issue?
Name - Schauna singh
Uno. - UIT2022860
SY IT

**Comment by 51tejalhajari** [comment]
> Can you assign me this issue? Name -> Isha Baviskar Cno. -> UCE2022427 SY Comp

yes you can work on this issue
