### ISSUE TITLE
Binary Search

### ISSUE THREAD

**Issue by sanskritisri13** [Mozilla-Campus-Club-Cummins/HacktoberFest23_MozillaCCEW#94]
Given a sorted array of size N and an integer K, find the position(0-based indexing) at which K is present in the array using binary search.

**Comment by RutvikaWagh** [comment]
I would like to work on this issue. Here are my details:
Name : Rutvika Wagh
CNO: UCE2022669
Year : Second Year

**Comment by vaishnavim141003** [comment]
I would like to work on this issue using python language .
Name-Vaishnavi Mahajan.(UIN2022739)
Cummins college of engineering.(SY)
Can you please assign this issue to me .

**Comment by sanskritisri13** [comment]
I will be assigning this issue to you by the end of the day.
Thank You!

**Comment by sanskritisri13** [comment]
@vaishnavim141003  the issue has been assigned to you try completing it as soon as possible.Apologies for the delay.
Thank You!
